server:
  port:  9001
spring:
  application:
    name: hongduten_base #这个是属于云服务器上面的数据库
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://118.25.234.16:3306/tensquare_base?characterEncoding=utf-8&useSSL=false
    username: root
    password: root
  jpa:
    show-sql: true
    database: mysql
    generate-ddl: true